# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
name = "shopify-app-react-cf"
handle = "shopify-app-react-cf"
application_url = "https://shopify-app-react-cf.workers.dev"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-app-react-cf.workers.dev/auth/callback",
  "https://shopify-app-react-cf.workers.dev/auth/shopify/callback",
  "https://shopify-app-react-cf.workers.dev/api/auth/callback",
]

[pos]
embedded = false
